const mongoose = require('mongoose');

const complianceReportSchema = new mongoose.Schema({
  // Report identification
  reportNumber: {
    type: String,
    unique: true,
    required: true
  },

  // Report details
  title: {
    type: String,
    required: true
  },

  description: String,

  // Report type
  reportType: {
    type: String,
    required: true,
    enum: [
      'audit_trail', 'financial_compliance', 'tax_compliance',
      'data_retention', 'user_access', 'security_events',
      'transaction_history', 'approval_compliance', 'sod_violations',
      'custom'
    ]
  },

  // Report period
  periodType: {
    type: String,
    enum: ['daily', 'weekly', 'monthly', 'quarterly', 'yearly', 'custom'],
    default: 'monthly'
  },

  startDate: {
    type: Date,
    required: true
  },

  endDate: {
    type: Date,
    required: true
  },

  // Criteria/filters used
  criteria: {
    entityTypes: [String],
    actions: [String],
    users: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
    complianceFlags: [String],
    customFilters: mongoose.Schema.Types.Mixed
  },

  // Report results
  findings: {
    totalRecords: { type: Number, default: 0 },
    criticalIssues: { type: Number, default: 0 },
    warnings: { type: Number, default: 0 },
    passed: { type: Number, default: 0 },
    
    details: [{
      severity: {
        type: String,
        enum: ['critical', 'high', 'medium', 'low', 'info'],
        default: 'info'
      },
      category: String,
      issue: String,
      description: String,
      recommendation: String,
      affectedRecords: [mongoose.Schema.Types.Mixed],
      evidenceLinks: [String]
    }]
  },

  // Summary and recommendations
  summary: String,
  recommendations: [String],

  // Compliance status
  complianceStatus: {
    type: String,
    enum: ['compliant', 'non_compliant', 'partially_compliant', 'under_review'],
    default: 'under_review'
  },

  // Report metadata
  generatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },

  reviewedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },

  approvedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },

  // Status workflow
  status: {
    type: String,
    enum: ['draft', 'pending_review', 'reviewed', 'approved', 'archived'],
    default: 'draft'
  },

  reviewDate: Date,
  approvalDate: Date,

  // File attachments
  attachments: [{
    filename: String,
    filepath: String,
    filesize: Number,
    mimetype: String,
    uploadedAt: { type: Date, default: Date.now }
  }],

  // Report template (if generated from template)
  template: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'ComplianceTemplate'
  },

  // Auto-generation settings
  isAutoGenerated: {
    type: Boolean,
    default: false
  },

  schedule: {
    frequency: {
      type: String,
      enum: ['daily', 'weekly', 'monthly', 'quarterly', 'yearly'],
    },
    nextRun: Date
  },

  // Audit trail for the report itself
  auditTrail: [{
    action: String,
    performedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    timestamp: { type: Date, default: Date.now },
    notes: String
  }],

  // Additional metadata
  metadata: {
    type: mongoose.Schema.Types.Mixed,
    default: {}
  }
}, {
  timestamps: true
});

// Indexes
complianceReportSchema.index({ reportNumber: 1 });
complianceReportSchema.index({ reportType: 1, startDate: -1 });
complianceReportSchema.index({ status: 1, createdAt: -1 });
complianceReportSchema.index({ generatedBy: 1 });
complianceReportSchema.index({ complianceStatus: 1 });

// Pre-save hook to generate report number
complianceReportSchema.pre('save', async function(next) {
  if (!this.reportNumber) {
    const date = new Date();
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    
    // Count reports created today
    const startOfDay = new Date(year, date.getMonth(), day);
    const endOfDay = new Date(year, date.getMonth(), day + 1);
    
    const count = await this.constructor.countDocuments({
      createdAt: { $gte: startOfDay, $lt: endOfDay }
    });
    
    this.reportNumber = `CR-${year}${month}${day}-${String(count + 1).padStart(4, '0')}`;
  }
  next();
});

// Instance methods

// Submit for review
complianceReportSchema.methods.submitForReview = async function() {
  if (this.status !== 'draft') {
    throw new Error('Only draft reports can be submitted for review');
  }
  
  this.status = 'pending_review';
  this.auditTrail.push({
    action: 'submitted_for_review',
    performedBy: this.generatedBy,
    timestamp: new Date()
  });
  
  return this.save();
};

// Review report
complianceReportSchema.methods.review = async function(reviewerId, notes) {
  if (this.status !== 'pending_review') {
    throw new Error('Report must be pending review');
  }
  
  this.status = 'reviewed';
  this.reviewedBy = reviewerId;
  this.reviewDate = new Date();
  this.auditTrail.push({
    action: 'reviewed',
    performedBy: reviewerId,
    timestamp: new Date(),
    notes
  });
  
  return this.save();
};

// Approve report
complianceReportSchema.methods.approve = async function(approverId, notes) {
  if (this.status !== 'reviewed') {
    throw new Error('Report must be reviewed before approval');
  }
  
  this.status = 'approved';
  this.approvedBy = approverId;
  this.approvalDate = new Date();
  this.auditTrail.push({
    action: 'approved',
    performedBy: approverId,
    timestamp: new Date(),
    notes
  });
  
  return this.save();
};

// Archive report
complianceReportSchema.methods.archive = async function(userId, notes) {
  this.status = 'archived';
  this.auditTrail.push({
    action: 'archived',
    performedBy: userId,
    timestamp: new Date(),
    notes
  });
  
  return this.save();
};

// Calculate compliance score
complianceReportSchema.methods.calculateComplianceScore = function() {
  const total = this.findings.totalRecords;
  if (total === 0) return 100;
  
  const passed = this.findings.passed || 0;
  return Math.round((passed / total) * 100);
};

// Static methods

// Generate report number
complianceReportSchema.statics.generateReportNumber = async function() {
  const date = new Date();
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  
  const startOfDay = new Date(year, date.getMonth(), day);
  const endOfDay = new Date(year, date.getMonth(), day + 1);
  
  const count = await this.countDocuments({
    createdAt: { $gte: startOfDay, $lt: endOfDay }
  });
  
  return `CR-${year}${month}${day}-${String(count + 1).padStart(4, '0')}`;
};

// Get reports due for generation
complianceReportSchema.statics.getDueReports = async function() {
  return this.find({
    isAutoGenerated: true,
    'schedule.nextRun': { $lte: new Date() },
    status: { $ne: 'archived' }
  });
};

// Virtuals
complianceReportSchema.virtual('complianceScore').get(function() {
  return this.calculateComplianceScore();
});

complianceReportSchema.virtual('durationDays').get(function() {
  if (!this.startDate || !this.endDate) return 0;
  const diff = this.endDate - this.startDate;
  return Math.ceil(diff / (1000 * 60 * 60 * 24));
});

const ComplianceReport = mongoose.model('ComplianceReport', complianceReportSchema);

module.exports = ComplianceReport;
